apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ewbz909ow-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ewbz909ow-python 
  name: ewbz909ow-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ewbz909ow-python 
